### ISSUE TITLE
Enable HTTPS only on server

### ISSUE THREAD

**Issue by jamesadarich** [jamesadarich/web-app-seed#13]
Sometimes you just want things to be secure all the time

**Comment by jamesrichford** [comment]
https://scotthelme.co.uk/hsts-the-missing-link-in-tls/

**Comment by jamesrichford** [comment]
SSL setup:

Check for LetsEncrypt domains in environment variables then use that
Check for certificates in folder then use them
Otherwise fail startup

Init should set up local certs for Dev

**Comment by jamesrichford** [comment]
+ webpack dev server https

**Comment by jamesadarich** [comment]
closing, set up should be in infrastructure
